-- GENERATED by scripts/gen_dbt_models.py from sql/02_dimensions.sql. Do not edit; change sql/ and regenerate.
{{ config(materialized='table') }}

select
    d::date as date_key,
    extract(year from d)::integer as year,
    extract(month from d)::integer as month,
    extract(quarter from d)::integer as quarter,
    strftime(d, '%Y-%m') as year_month,
    date_trunc('month', d)::date as month_start,
    (d::date between '{{ var('study_start') }}'::date and '{{ var('study_end') }}'::date) as in_study_window
from generate_series(date '2007-01-01', '{{ var('study_end') }}'::date, interval 1 day) as t(d)
