-- GENERATED by scripts/gen_dbt_models.py from sql/02_dimensions.sql. Do not edit; change sql/ and regenerate.
{{ config(materialized='table') }}

select * from (values
    ('inpatient', 'Inpatient (institutional, hospital stays)', 'CMS inpatient claims file', 1),
    ('outpatient', 'Outpatient (institutional, hospital outpatient)', 'CMS outpatient claims file', 2),
    ('carrier', 'Carrier (professional, physician and supplier)', 'CMS carrier claims file', 3)
) as t(care_setting, description, source_file_type, sort_order)
