-- GENERATED by scripts/gen_dbt_models.py from sql/02_dimensions.sql. Do not edit; change sql/ and regenerate.
{{ config(materialized='table') }}

with codes as (
    select code from {{ ref('stg_hcpcs_long') }}
    union select hcpcs from {{ ref('stg_carrier_line') }} where hcpcs is not null
)
select
    row_number() over (order by code) as procedure_key,
    code as procedure_code,
    'HCPCS' as code_system,
    hcpcs_valid(code) as format_valid,
    hcpcs_group(code) as procedure_group,
    list_contains({{ duckdb_varchar_list(var('ed_codes')) }}, code) as is_ed_proxy_code
from codes
