-- GENERATED by scripts/gen_dbt_models.py from sql/02_dimensions.sql. Do not edit; change sql/ and regenerate.
{{ config(materialized='table') }}

select
    row_number() over (order by beneficiary_id) as beneficiary_key,
    beneficiary_id,
    min(birth_date) as birth_date,
    max(death_date) as death_date,
    (max(death_date) is not null) as deceased,
    arg_max(sex_code, bene_year) as sex_code,
    case arg_max(sex_code, bene_year) when '1' then 'Male' when '2' then 'Female' else 'Unknown' end as sex,
    arg_max(race_code, bene_year) as race_code,
    case arg_max(race_code, bene_year) when '1' then 'White' when '2' then 'Black'
         when '3' then 'Other' when '5' then 'Hispanic' else 'Unknown' end as race,
    arg_max(state_code, bene_year) as state_code,
    bool_or(esrd_code = 'Y') as ever_esrd,
    min(bene_year) as first_year,
    max(bene_year) as last_year
from {{ ref('stg_beneficiary_year') }}
group by beneficiary_id
