-- GENERATED by scripts/gen_dbt_models.py from sql/02_dimensions.sql. Do not edit; change sql/ and regenerate.
{{ config(materialized='table') }}

with codes as (select code, count(*) as occurrences from {{ ref('stg_dx_long') }} group by code)
select
    row_number() over (order by c.code) as diagnosis_key,
    c.code as diagnosis_code,
    'ICD-9-CM' as code_system,
    icd9_valid(c.code) as format_valid,
    m.ccs_category,
    case when m.ccs_category is not null then m.ccs_category_name
         when icd9_valid(c.code) then 'Unmapped (valid format, not in CCS 2015)'
         else 'Invalid code format' end as ccs_category_name,
    (m.ccs_category is not null) as is_mapped,
    c.occurrences
from codes c
left join {{ source('claims_raw', 'ref_ccs_dx') }} m on m.icd9_code = c.code
