-- GENERATED by scripts/gen_dbt_models.py from sql/02_dimensions.sql. Do not edit; change sql/ and regenerate.
{{ config(materialized='table') }}

with ids as (
    select 'facility' as provider_type, facility_id as provider_id, 'inpatient_facility' as source_role
      from {{ ref('stg_ip') }} where facility_id is not null
    union all select 'facility', facility_id, 'outpatient_facility' from {{ ref('stg_op') }} where facility_id is not null
    union all select 'npi', attending_npi, 'inpatient_attending' from {{ ref('stg_ip') }} where attending_npi is not null
    union all select 'npi', operating_npi, 'inpatient_operating' from {{ ref('stg_ip') }} where operating_npi is not null
    union all select 'npi', other_npi, 'inpatient_other' from {{ ref('stg_ip') }} where other_npi is not null
    union all select 'npi', attending_npi, 'outpatient_attending' from {{ ref('stg_op') }} where attending_npi is not null
    union all select 'npi', operating_npi, 'outpatient_operating' from {{ ref('stg_op') }} where operating_npi is not null
    union all select 'npi', other_npi, 'outpatient_other' from {{ ref('stg_op') }} where other_npi is not null
    union all select 'npi', npi, 'carrier_performing' from {{ ref('stg_carrier_line') }} where npi is not null
)
select
    row_number() over (order by provider_type, provider_id) as provider_key,
    provider_type,
    provider_id,
    list_sort(list_distinct(list(source_role))) as source_roles
from ids
group by provider_type, provider_id
