-- GENERATED by scripts/gen_dbt_models.py from sql/03_claim_facts.sql. Do not edit; change sql/ and regenerate.
{{ config(materialized='table') }}

with ip as (
    select 'inpatient' as setting, beneficiary_id, claim_id,
           min(from_date) as from_date, max(thru_date) as thru_date,
           min(admit_date) as admit_date, max(discharge_date) as discharge_date,
           coalesce(sum(clm_pmt_amt), 0)::decimal(14, 2) as payment_amount,
           count(*) as segment_count, null::integer as line_count,
           arg_min(facility_id, segment) filter (where facility_id is not null) as facility_id,
           arg_min(dx_1, segment) filter (where dx_1 is not null) as primary_dx,
           max(source_utilization_days) as source_utilization_days
    from {{ ref('stg_ip') }} group by beneficiary_id, claim_id
), op as (
    select 'outpatient' as setting, beneficiary_id, claim_id,
           min(from_date) as from_date, max(thru_date) as thru_date,
           null::date as admit_date, null::date as discharge_date,
           coalesce(sum(clm_pmt_amt), 0)::decimal(14, 2) as payment_amount,
           count(*) as segment_count, null::integer as line_count,
           arg_min(facility_id, segment) filter (where facility_id is not null) as facility_id,
           arg_min(dx_1, segment) filter (where dx_1 is not null) as primary_dx,
           null::integer as source_utilization_days
    from {{ ref('stg_op') }} group by beneficiary_id, claim_id
), ca as (
    select 'carrier' as setting, c.beneficiary_id, c.claim_id, c.from_date, c.thru_date,
           null::date as admit_date, null::date as discharge_date,
           coalesce(l.payment, 0)::decimal(14, 2) as payment_amount,
           1 as segment_count, coalesce(l.line_count, 0)::integer as line_count,
           null::varchar as facility_id, c.dx_1 as primary_dx, null::integer as source_utilization_days
    from {{ ref('stg_carrier_claim') }} c
    left join (select beneficiary_id, claim_id, sum(line_nch_pmt_amt) as payment, count(*) as line_count
               from {{ ref('stg_carrier_line') }} group by 1, 2) l using (beneficiary_id, claim_id)
), unioned as (
    select * from ip union all select * from op union all select * from ca
), flagged as (
    select
        setting || ':' || beneficiary_id || ':' || claim_id as claim_key,
        *,
        case setting when 'carrier' then 'LINE_NCH_PMT_AMT_1..13 (sum of lines)'
                     else 'CLM_PMT_AMT (sum of segments)' end as payment_source_field,
        (from_date is not null and thru_date is not null and from_date <= thru_date
         and (setting <> 'inpatient'
              or (admit_date is not null and discharge_date is not null and admit_date <= discharge_date))) as date_valid,
        case when setting = 'inpatient' then coalesce(admit_date, from_date) else from_date end as service_date,
        primary_dx is not null as has_primary_dx,
        icd9_valid(primary_dx) as primary_dx_valid
    from unioned
), dated as (
    select *,
           coalesce(service_date between '{{ var('study_start') }}'::date and '{{ var('study_end') }}'::date, false) as in_study_window
    from flagged
)
select *,
       (date_valid and in_study_window) as is_analytic,
       extract(year from service_date)::integer as claim_year,
       date_trunc('month', service_date)::date as month_start
from dated
