-- GENERATED by scripts/gen_dbt_models.py from sql/03_claim_facts.sql. Do not edit; change sql/ and regenerate.
{{ config(materialized='table') }}

select
    b.beneficiary_id,
    b.bene_year as year,
    b.hi_coverage_months, b.smi_coverage_months, b.hmo_coverage_months, b.plan_coverage_months,
    b.sp_alzhdmta, b.sp_chf, b.sp_chrnkidn, b.sp_cncr, b.sp_copd, b.sp_depressn, b.sp_diabetes,
    b.sp_ischmcht, b.sp_osteoprs, b.sp_ra_oa, b.sp_strketia,
    (coalesce(b.sp_alzhdmta, false)::integer + coalesce(b.sp_chf, false)::integer + coalesce(b.sp_chrnkidn, false)::integer
     + coalesce(b.sp_cncr, false)::integer + coalesce(b.sp_copd, false)::integer + coalesce(b.sp_depressn, false)::integer
     + coalesce(b.sp_diabetes, false)::integer + coalesce(b.sp_ischmcht, false)::integer
     + coalesce(b.sp_osteoprs, false)::integer + coalesce(b.sp_ra_oa, false)::integer
     + coalesce(b.sp_strketia, false)::integer) as chronic_condition_count,
    b.medreimb_ip, b.benres_ip, b.pppymt_ip, b.medreimb_op, b.benres_op, b.pppymt_op,
    b.medreimb_car, b.benres_car, b.pppymt_car,
    case when d.death_date is null or extract(year from d.death_date) > b.bene_year then 12
         when extract(year from d.death_date) < b.bene_year then 0
         else extract(month from d.death_date)::integer end as months_alive,
    greatest(0, least(coalesce(b.hi_coverage_months, 0),
        case when d.death_date is null or extract(year from d.death_date) > b.bene_year then 12
             when extract(year from d.death_date) < b.bene_year then 0
             else extract(month from d.death_date)::integer end)) as member_months
from {{ ref('stg_beneficiary_year') }} b
join {{ ref('dim_beneficiary') }} d using (beneficiary_id)
