-- GENERATED by scripts/gen_dbt_models.py from sql/03_claim_facts.sql. Do not edit; change sql/ and regenerate.
{{ config(materialized='table') }}

select 'carrier:' || beneficiary_id || ':' || claim_id as claim_key, 'carrier' as setting, beneficiary_id, claim_id,
       line_num, hcpcs as procedure_code, npi as performing_npi, tax_num, line_dx as line_diagnosis_code,
       line_nch_pmt_amt, line_bene_ptb_ddctbl_amt, line_bene_prmry_pyr_pd_amt, line_coinsrnc_amt,
       line_alowd_chrg_amt, line_prcsg_ind_cd
from {{ ref('stg_carrier_line') }}
union all
select setting || ':' || beneficiary_id || ':' || claim_id, setting, beneficiary_id, claim_id,
       (coalesce(try_cast(segment as integer), 1) - 1) * 45 + line_num, code, null, null, null,
       null::decimal(14, 2), null::decimal(14, 2), null::decimal(14, 2), null::decimal(14, 2),
       null::decimal(14, 2), null
from (select distinct * from {{ ref('stg_hcpcs_long') }})
