-- GENERATED by scripts/gen_dbt_models.py from sql/03_claim_facts.sql. Do not edit; change sql/ and regenerate.
{{ config(materialized='table') }}

select setting || ':' || beneficiary_id || ':' || claim_id as claim_key, setting, beneficiary_id, claim_id,
       code as diagnosis_code, min(pos) as first_position
from {{ ref('stg_dx_long') }}
group by setting, beneficiary_id, claim_id, code
