-- GENERATED by scripts/gen_dbt_models.py from sql/03_claim_facts.sql. Do not edit; change sql/ and regenerate.
{{ config(materialized='table') }}

with claims as (
    select claim_key, beneficiary_id, claim_id, admit_date, discharge_date, payment_amount, facility_id,
           primary_dx, source_utilization_days
    from {{ ref('fact_claim_header') }} where setting = 'inpatient' and is_analytic
), ordered as (
    select *, max(discharge_date) over (
        partition by beneficiary_id order by admit_date, claim_id
        rows between unbounded preceding and 1 preceding) as prior_max_discharge
    from claims
), numbered as (
    select *, sum(case when prior_max_discharge is null or admit_date > prior_max_discharge then 1 else 0 end)
        over (partition by beneficiary_id order by admit_date, claim_id rows unbounded preceding) as stay_seq
    from ordered
)
select
    beneficiary_id || ':' || stay_seq as stay_key,
    beneficiary_id,
    stay_seq,
    min(admit_date) as admit_date,
    max(discharge_date) as discharge_date,
    date_diff('day', min(admit_date), max(discharge_date)) as length_of_stay_days,
    count(*) as claim_count,
    sum(payment_amount)::decimal(14, 2) as payment_amount,
    arg_min(facility_id, admit_date) as admitting_facility_id,
    arg_min(primary_dx, admit_date) as primary_dx,
    max(source_utilization_days) as source_utilization_days,
    extract(year from min(admit_date))::integer as admit_year,
    date_trunc('month', min(admit_date))::date as admit_month
from numbered
group by beneficiary_id, stay_seq
