-- GENERATED by scripts/gen_dbt_models.py from sql/01_staging.sql. Do not edit; change sql/ and regenerate.
{% macro create_claims_sql_macros() %}
-- DuckDB scalar macros used by the models, created in the target database before any model runs.
create or replace macro norm_code(x) as nullif(upper(replace(replace(trim(x), '.', ''), ' ', '')), '');
create or replace macro to_date8(x) as try_strptime(x, '%Y%m%d')::date;
create or replace macro to_amt(x) as try_cast(x as decimal(14, 2));
create or replace macro icd9_valid(c) as (
    c is not null and (regexp_full_match(c, '[0-9]{3}[0-9]{0,2}')
                       or regexp_full_match(c, 'V[0-9]{2}[0-9]{0,2}')
                       or regexp_full_match(c, 'E[0-9]{3}[0-9]?')));
create or replace macro hcpcs_valid(c) as (c is not null and regexp_full_match(c, '[0-9A-Z][0-9]{3}[0-9A-Z]'));
create or replace macro hcpcs_group(c) as (
    case
        when not coalesce(hcpcs_valid(c), false) then 'Invalid or missing'
        when regexp_full_match(c, '[0-9]{4}[FT]') then 'CPT category II and III'
        when regexp_full_match(c, '[0-9]{5}') then
            case when c::integer between 99201 and 99499 then 'Evaluation and management'
                 when c::integer between 100 and 1999 then 'Anesthesia'
                 when c::integer between 10021 and 69990 then 'Surgery'
                 when c::integer between 70010 and 79999 then 'Radiology'
                 when c::integer between 80047 and 89398 then 'Pathology and laboratory'
                 when c::integer between 90281 and 99199 or c::integer between 99500 and 99607 then 'Medicine'
                 else 'Unclassified' end
        when regexp_full_match(c, '[0-9].*') then 'Unclassified'
        else case substr(c, 1, 1)
            when 'A' then 'Transportation, medical and surgical supplies'
            when 'B' then 'Enteral and parenteral therapy'
            when 'C' then 'Outpatient PPS temporary codes'
            when 'D' then 'Dental'
            when 'E' then 'Durable medical equipment'
            when 'G' then 'Temporary procedures and professional services'
            when 'H' then 'Behavioral health and substance abuse'
            when 'J' then 'Drugs administered other than oral'
            when 'K' then 'Temporary durable medical equipment'
            when 'L' then 'Orthotic and prosthetic procedures'
            when 'M' then 'Other medical services'
            when 'P' then 'Pathology and laboratory'
            when 'Q' then 'Temporary codes'
            when 'R' then 'Diagnostic radiology'
            when 'S' then 'Private payer temporary codes'
            when 'T' then 'State Medicaid temporary codes'
            when 'V' then 'Vision and hearing'
            else 'Unclassified' end
    end);
{% endmacro %}
