-- GENERATED by scripts/gen_dbt_models.py from sql/06_quality_mart.sql. Do not edit; change sql/ and regenerate.
{{ config(materialized='table') }}

with prior as (
    select f.beneficiary_id, f.year,
           p.beneficiary_id is not null as has_prior_year,
           coalesce(p.chronic_condition_count, 0) as prior_chronic_conditions,
           coalesce(s.admissions, 0) as prior_admissions,
           coalesce(s.payment_amount, 0) as prior_paid_amount
    from {{ ref('fact_beneficiary_year') }} f
    left join {{ ref('fact_beneficiary_year') }} p on p.beneficiary_id = f.beneficiary_id and p.year = f.year - 1
    left join {{ ref('mart_beneficiary_year_summary') }} s on s.beneficiary_id = f.beneficiary_id and s.year = f.year - 1
), scored as (
    select *,
           case when prior_chronic_conditions <= {{ var('comorb_low_max') }} then 0
                when prior_chronic_conditions <= {{ var('comorb_medium_max') }} then 1 else 2 end as comorbidity_points,
           case when prior_admissions = 0 then 0 when prior_admissions = 1 then {{ var('adm_one') }} else {{ var('adm_two_plus') }} end as admission_points,
           case when prior_paid_amount >= cast({{ var('paid_high_min') }} as double) then 2
                when prior_paid_amount >= cast({{ var('paid_medium_min') }} as double) then 1 else 0 end as paid_points
    from prior
)
select beneficiary_id, year, has_prior_year, prior_chronic_conditions, prior_admissions, prior_paid_amount,
       comorbidity_points, admission_points, paid_points,
       comorbidity_points + admission_points + paid_points as risk_score,
       case when not has_prior_year then 'not_assessed'
            when comorbidity_points + admission_points + paid_points <= {{ var('tier_low_max') }} then 'low'
            when comorbidity_points + admission_points + paid_points <= {{ var('tier_medium_max') }} then 'medium'
            else 'high' end as utilization_risk_tier
from scored
