-- GENERATED by scripts/gen_dbt_models.py from sql/05_payment_mart.sql. Do not edit; change sql/ and regenerate.
{{ config(materialized='table') }}

select month_start, setting, payment_source_field,
       count(*) as claims,
       sum(payment_amount)::decimal(16, 2) as payment_amount,
       count(*) filter (where payment_amount < 0) as negative_payment_claims,
       count(*) filter (where payment_amount = 0) as zero_payment_claims
from {{ ref('fact_claim_header') }}
where is_analytic
group by month_start, setting, payment_source_field
