-- GENERATED by scripts/gen_dbt_models.py from sql/05_payment_mart.sql. Do not edit; change sql/ and regenerate.
{{ config(materialized='table') }}

select claim_year as year, setting, payment_source_field,
       count(*) as claims,
       sum(payment_amount)::decimal(16, 2) as payment_amount,
       count(distinct beneficiary_id) as paid_beneficiaries
from {{ ref('fact_claim_header') }}
where is_analytic
group by claim_year, setting, payment_source_field
