-- GENERATED by scripts/gen_dbt_models.py from sql/05_payment_mart.sql. Do not edit; change sql/ and regenerate.
{{ config(materialized='table') }}

with ranked as (
    select year, beneficiary_id, payment_amount,
           row_number() over (partition by year order by payment_amount desc, beneficiary_id) as rnk,
           count(*) over (partition by year) as n
    from {{ ref('mart_beneficiary_year_summary') }}
)
select
    year,
    max(n) as beneficiaries,
    ceil(max(n) * cast({{ var('top_share_percent') }} as double) / 100.0)::integer as top_count,
    coalesce(sum(payment_amount) filter (where rnk <= ceil(n * cast({{ var('top_share_percent') }} as double) / 100.0)), 0)::decimal(16, 2) as top_payment,
    sum(payment_amount)::decimal(16, 2) as total_payment,
    case when sum(payment_amount) <> 0
         then sum(payment_amount) filter (where rnk <= ceil(n * cast({{ var('top_share_percent') }} as double) / 100.0)) / sum(payment_amount) end as top_share,
    arg_min(beneficiary_id, rnk) as top_beneficiary_id
from ranked
group by year
