-- GENERATED by scripts/gen_dbt_models.py from sql/06_quality_mart.sql. Do not edit; change sql/ and regenerate.
{{ config(materialized='table') }}

with base as (
    select s.stay_key, s.beneficiary_id, s.admit_date, s.discharge_date,
           extract(year from s.discharge_date)::integer as discharge_year,
           coalesce(b.death_date between s.admit_date and s.discharge_date, false) as died_in_stay,
           (s.discharge_date > '{{ var('study_end') }}'::date - {{ var('readmission_days') }}::integer) as insufficient_followup,
           (select count(*) from {{ ref('fact_inpatient_stay') }} n
             where n.beneficiary_id = s.beneficiary_id and n.admit_date > s.discharge_date
               and n.admit_date <= s.discharge_date + {{ var('readmission_days') }}::integer) as readmissions_in_window
    from {{ ref('fact_inpatient_stay') }} s
    join {{ ref('dim_beneficiary') }} b using (beneficiary_id)
)
select *,
       (not died_in_stay and not insufficient_followup) as eligible_index,
       (not died_in_stay and not insufficient_followup and readmissions_in_window > 0) as readmitted
from base
