-- GENERATED by scripts/gen_dbt_models.py from sql/05_payment_mart.sql. Do not edit; change sql/ and regenerate.
{{ config(materialized='table') }}

select s.year, b.sex, b.race,
       case when s.year - extract(year from b.birth_date) < 65 then 'Under 65'
            when s.year - extract(year from b.birth_date) < 75 then '65-74'
            when s.year - extract(year from b.birth_date) < 85 then '75-84'
            else '85 and over' end as age_band,
       count(*) as beneficiaries,
       sum(s.member_months) as member_months,
       sum(s.claims) as claims,
       sum(s.payment_amount)::decimal(16, 2) as payment_amount,
       sum(s.admissions) as admissions
from {{ ref('mart_beneficiary_year_summary') }} s
join {{ ref('dim_beneficiary') }} b using (beneficiary_id)
group by 1, 2, 3, 4
