-- GENERATED by scripts/gen_dbt_models.py from sql/04_utilization_mart.sql. Do not edit; change sql/ and regenerate.
{{ config(materialized='table') }}

select f.beneficiary_id, f.year, t.m as month, make_date(f.year, t.m, 1) as month_start,
       (t.m <= f.member_months) as eligible
from {{ ref('fact_beneficiary_year') }} f, unnest(range(1, 13)) as t(m)
