-- GENERATED by scripts/gen_dbt_models.py from sql/06_quality_mart.sql. Do not edit; change sql/ and regenerate.
{{ config(materialized='table') }}

select r.discharge_year as year,
       coalesce(m.utilization_risk_tier, 'not_assessed') as utilization_risk_tier,
       count(*) filter (where r.eligible_index) as eligible_index_stays,
       count(*) filter (where r.readmitted) as readmitted_stays,
       case when count(*) filter (where r.eligible_index) > 0
            then (count(*) filter (where r.readmitted))::double / (count(*) filter (where r.eligible_index)) end as readmission_rate,
       count(*) filter (where r.died_in_stay) as excluded_died_in_stay,
       count(*) filter (where r.insufficient_followup and not r.died_in_stay) as excluded_insufficient_followup,
       count(*) as stays_considered
from {{ ref('mart_readmission_index') }} r
left join {{ ref('mart_member_risk') }} m on m.beneficiary_id = r.beneficiary_id and m.year = r.discharge_year
group by r.discharge_year, coalesce(m.utilization_risk_tier, 'not_assessed')
