-- GENERATED by scripts/gen_dbt_models.py from sql/04_utilization_mart.sql. Do not edit; change sql/ and regenerate.
{{ config(materialized='table') }}

with members as (
    select month_start, count(*) filter (where eligible) as members from {{ ref('mart_member_month') }} group by 1
), claims as (
    select setting, month_start, count(*) as claims, count(distinct beneficiary_id) as unique_beneficiaries
    from {{ ref('fact_claim_header') }} where is_analytic group by 1, 2
), admits as (
    select admit_month as month_start, count(*) as admissions from {{ ref('fact_inpatient_stay') }} group by 1
), ed_claims as (
    select distinct claim_key from {{ ref('fact_claim_line') }}
    where setting = 'outpatient' and list_contains({{ duckdb_varchar_list(var('ed_codes')) }}, procedure_code)
), ed as (
    select h.month_start, count(*) as ed_proxy_visits
    from {{ ref('fact_claim_header') }} h join ed_claims e using (claim_key)
    where h.setting = 'outpatient' and h.is_analytic group by 1
), lines as (
    select h.month_start, count(*) as carrier_service_lines
    from {{ ref('fact_claim_line') }} l join {{ ref('fact_claim_header') }} h using (claim_key)
    where h.setting = 'carrier' and h.is_analytic group by 1
)
select
    m.month_start,
    s.care_setting as setting,
    m.members,
    coalesce(c.claims, 0) as claims,
    coalesce(c.unique_beneficiaries, 0) as unique_beneficiaries,
    case when s.care_setting = 'inpatient' then coalesce(a.admissions, 0) end as admissions,
    case when s.care_setting = 'outpatient' then coalesce(e.ed_proxy_visits, 0) end as ed_proxy_visits,
    case when s.care_setting = 'outpatient' then coalesce(c.claims, 0) end as outpatient_visits,
    case when s.care_setting = 'carrier' then coalesce(l.carrier_service_lines, 0) end as carrier_service_lines,
    case when m.members > 0 then coalesce(c.claims, 0) * 1000.0 / m.members end as claims_per_1000_members
from members m
cross join {{ ref('dim_care_setting') }} s
left join claims c on c.month_start = m.month_start and c.setting = s.care_setting
left join admits a on a.month_start = m.month_start
left join ed e on e.month_start = m.month_start
left join lines l on l.month_start = m.month_start
where m.month_start is not null
