-- GENERATED by scripts/gen_dbt_models.py from sql/05_payment_mart.sql. Do not edit; change sql/ and regenerate.
{{ config(materialized='table') }}

select f.beneficiary_id, f.year, f.member_months, f.chronic_condition_count,
       coalesce(c.claims, 0) as claims,
       coalesce(c.payment, 0)::decimal(16, 2) as payment_amount,
       coalesce(a.admissions, 0) as admissions
from {{ ref('fact_beneficiary_year') }} f
left join (select beneficiary_id, claim_year as year, count(*) as claims, sum(payment_amount) as payment
           from {{ ref('fact_claim_header') }} where is_analytic group by 1, 2) c
       on c.beneficiary_id = f.beneficiary_id and c.year = f.year
left join (select beneficiary_id, admit_year as year, count(*) as admissions
           from {{ ref('fact_inpatient_stay') }} group by 1, 2) a
       on a.beneficiary_id = f.beneficiary_id and a.year = f.year
