-- GENERATED by scripts/gen_dbt_models.py from sql/06_quality_mart.sql. Do not edit; change sql/ and regenerate.
{{ config(materialized='table') }}

select 'primary_diagnosis_ccs' as condition_type, h.claim_year as year, h.setting,
       case when h.primary_dx is null then 'missing'
            when d.ccs_category is not null then d.ccs_category::varchar
            when h.primary_dx_valid then 'unmapped_valid'
            else 'invalid_format' end as condition_id,
       case when h.primary_dx is null then 'Missing primary diagnosis'
            when d.ccs_category is not null then d.ccs_category_name
            when h.primary_dx_valid then 'Unmapped (valid format, not in CCS 2015)'
            else 'Invalid code format' end as condition_name,
       count(*) as claims,
       count(distinct h.beneficiary_id) as beneficiaries,
       sum(h.payment_amount)::decimal(16, 2) as payment_amount,
       null::bigint as denominator_beneficiaries
from {{ ref('fact_claim_header') }} h
left join {{ ref('dim_diagnosis') }} d on d.diagnosis_code = h.primary_dx
where h.is_analytic
group by 1, 2, 3, 4, 5
union all
select 'chronic_condition_flag', year, 'all', condition, upper(replace(condition, 'sp_', '')) as label,
       0, count(*) filter (where flag), null, count(*)
from (unpivot (select beneficiary_id, year, sp_alzhdmta, sp_chf, sp_chrnkidn, sp_cncr, sp_copd, sp_depressn,
                      sp_diabetes, sp_ischmcht, sp_osteoprs, sp_ra_oa, sp_strketia from {{ ref('fact_beneficiary_year') }})
      on sp_alzhdmta, sp_chf, sp_chrnkidn, sp_cncr, sp_copd, sp_depressn, sp_diabetes, sp_ischmcht,
         sp_osteoprs, sp_ra_oa, sp_strketia into name condition value flag)
group by year, condition
