-- GENERATED by scripts/gen_dbt_models.py from sql/04_utilization_mart.sql. Do not edit; change sql/ and regenerate.
{{ config(materialized='table') }}

with members as (
    select year, sum(member_months) as member_months, count(*) as beneficiaries from {{ ref('fact_beneficiary_year') }} group by 1
), claims as (
    select setting, claim_year as year, count(*) as claims, count(distinct beneficiary_id) as unique_beneficiaries
    from {{ ref('fact_claim_header') }} where is_analytic group by 1, 2
), admits as (
    select admit_year as year, count(*) as admissions, sum(length_of_stay_days) as total_length_of_stay_days
    from {{ ref('fact_inpatient_stay') }} group by 1
), ed_claims as (
    select distinct claim_key from {{ ref('fact_claim_line') }}
    where setting = 'outpatient' and list_contains({{ duckdb_varchar_list(var('ed_codes')) }}, procedure_code)
), ed as (
    select h.claim_year as year, count(*) as ed_proxy_visits
    from {{ ref('fact_claim_header') }} h join ed_claims e using (claim_key)
    where h.setting = 'outpatient' and h.is_analytic group by 1
), lines as (
    select h.claim_year as year, count(*) as carrier_service_lines
    from {{ ref('fact_claim_line') }} l join {{ ref('fact_claim_header') }} h using (claim_key)
    where h.setting = 'carrier' and h.is_analytic group by 1
)
select
    m.year,
    s.care_setting as setting,
    m.beneficiaries,
    m.member_months,
    m.member_months / 12.0 as member_years,
    coalesce(c.claims, 0) as claims,
    coalesce(c.unique_beneficiaries, 0) as unique_beneficiaries,
    case when s.care_setting = 'inpatient' then coalesce(a.admissions, 0) end as admissions,
    case when s.care_setting = 'inpatient' then coalesce(a.total_length_of_stay_days, 0) end as total_length_of_stay_days,
    case when s.care_setting = 'outpatient' then coalesce(e.ed_proxy_visits, 0) end as ed_proxy_visits,
    case when s.care_setting = 'outpatient' then coalesce(c.claims, 0) end as outpatient_visits,
    case when s.care_setting = 'carrier' then coalesce(l.carrier_service_lines, 0) end as carrier_service_lines
from members m
cross join {{ ref('dim_care_setting') }} s
left join claims c on c.year = m.year and c.setting = s.care_setting
left join admits a on a.year = m.year
left join ed e on e.year = m.year
left join lines l on l.year = m.year
