-- GENERATED by scripts/gen_dbt_models.py from sql/01_staging.sql. Do not edit; change sql/ and regenerate.
{{ config(materialized='view') }}

select * exclude (dup_rank) from {{ ref('stg_op_all') }} where dup_rank = 1
