-- GENERATED by scripts/gen_dbt_models.py from sql/01_staging.sql. Do not edit; change sql/ and regenerate.
{{ config(materialized='table') }}

select
    "DESYNPUF_ID" as beneficiary_id,
    "CLM_ID" as claim_id,
    coalesce("SEGMENT", '1') as segment,
    to_date8("CLM_FROM_DT") as from_date,
    to_date8("CLM_THRU_DT") as thru_date,
    "PRVDR_NUM" as facility_id,
    to_amt("CLM_PMT_AMT") as clm_pmt_amt,
    to_amt("NCH_PRMRY_PYR_CLM_PD_AMT") as nch_prmry_pyr_clm_pd_amt,
    "AT_PHYSN_NPI" as attending_npi,
    "OP_PHYSN_NPI" as operating_npi,
    "OT_PHYSN_NPI" as other_npi,
    to_date8("CLM_ADMSN_DT") as admit_date,
    to_date8("NCH_BENE_DSCHRG_DT") as discharge_date,
    try_cast("CLM_UTLZTN_DAY_CNT" as integer) as source_utilization_days,
    "CLM_DRG_CD" as drg_code,
    norm_code("ADMTNG_ICD9_DGNS_CD") as admitting_dx,
    norm_code("ICD9_DGNS_CD_1") as dx_1, norm_code("ICD9_DGNS_CD_2") as dx_2,
    norm_code("ICD9_DGNS_CD_3") as dx_3, norm_code("ICD9_DGNS_CD_4") as dx_4,
    norm_code("ICD9_DGNS_CD_5") as dx_5, norm_code("ICD9_DGNS_CD_6") as dx_6,
    norm_code("ICD9_DGNS_CD_7") as dx_7, norm_code("ICD9_DGNS_CD_8") as dx_8,
    norm_code("ICD9_DGNS_CD_9") as dx_9, norm_code("ICD9_DGNS_CD_10") as dx_10,
    source_file,
    row_number() over (partition by "DESYNPUF_ID", "CLM_ID", coalesce("SEGMENT", '1')
                       order by source_file) as dup_rank
from {{ source('claims_raw', 'raw_inpatient') }}
