-- GENERATED by scripts/gen_dbt_models.py from sql/01_staging.sql. Do not edit; change sql/ and regenerate.
{{ config(materialized='table') }}

select
    "DESYNPUF_ID" as beneficiary_id,
    bene_year,
    to_date8("BENE_BIRTH_DT") as birth_date,
    to_date8("BENE_DEATH_DT") as death_date,
    "BENE_SEX_IDENT_CD" as sex_code,
    "BENE_RACE_CD" as race_code,
    "BENE_ESRD_IND" as esrd_code,
    "SP_STATE_CODE" as state_code,
    "BENE_COUNTY_CD" as county_code,
    try_cast("BENE_HI_CVRAGE_TOT_MONS" as integer) as hi_coverage_months,
    try_cast("BENE_SMI_CVRAGE_TOT_MONS" as integer) as smi_coverage_months,
    try_cast("BENE_HMO_CVRAGE_TOT_MONS" as integer) as hmo_coverage_months,
    try_cast("PLAN_CVRG_MOS_NUM" as integer) as plan_coverage_months,
    ("SP_ALZHDMTA" = '1') as sp_alzhdmta,
    ("SP_CHF" = '1') as sp_chf,
    ("SP_CHRNKIDN" = '1') as sp_chrnkidn,
    ("SP_CNCR" = '1') as sp_cncr,
    ("SP_COPD" = '1') as sp_copd,
    ("SP_DEPRESSN" = '1') as sp_depressn,
    ("SP_DIABETES" = '1') as sp_diabetes,
    ("SP_ISCHMCHT" = '1') as sp_ischmcht,
    ("SP_OSTEOPRS" = '1') as sp_osteoprs,
    ("SP_RA_OA" = '1') as sp_ra_oa,
    ("SP_STRKETIA" = '1') as sp_strketia,
    to_amt("MEDREIMB_IP") as medreimb_ip,
    to_amt("BENRES_IP") as benres_ip,
    to_amt("PPPYMT_IP") as pppymt_ip,
    to_amt("MEDREIMB_OP") as medreimb_op,
    to_amt("BENRES_OP") as benres_op,
    to_amt("PPPYMT_OP") as pppymt_op,
    to_amt("MEDREIMB_CAR") as medreimb_car,
    to_amt("BENRES_CAR") as benres_car,
    to_amt("PPPYMT_CAR") as pppymt_car
from {{ source('claims_raw', 'raw_beneficiary') }}
qualify row_number() over (partition by "DESYNPUF_ID", bene_year order by source_file) = 1
