-- GENERATED by scripts/gen_dbt_models.py from sql/01_staging.sql. Do not edit; change sql/ and regenerate.
{{ config(materialized='table') }}

select
    "DESYNPUF_ID" as beneficiary_id,
    "CLM_ID" as claim_id,
    to_date8("CLM_FROM_DT") as from_date,
    to_date8("CLM_THRU_DT") as thru_date,
    norm_code("ICD9_DGNS_CD_1") as dx_1, norm_code("ICD9_DGNS_CD_2") as dx_2,
    norm_code("ICD9_DGNS_CD_3") as dx_3, norm_code("ICD9_DGNS_CD_4") as dx_4,
    norm_code("ICD9_DGNS_CD_5") as dx_5, norm_code("ICD9_DGNS_CD_6") as dx_6,
    norm_code("ICD9_DGNS_CD_7") as dx_7, norm_code("ICD9_DGNS_CD_8") as dx_8,
    source_file,
    row_number() over (partition by "DESYNPUF_ID", "CLM_ID" order by source_file) as dup_rank
from {{ source('claims_raw', 'raw_carrier') }}
