-- GENERATED by scripts/gen_dbt_models.py from sql/01b_staging_unpivot.sql. Do not edit; change sql/ and regenerate.
{{ config(materialized='table') }}

select * from (
select 'inpatient' as setting, beneficiary_id, claim_id, segment, unnest([{'pos': 0, 'code': admitting_dx}, {'pos': 1, 'code': dx_1}, {'pos': 2, 'code': dx_2}, {'pos': 3, 'code': dx_3}, {'pos': 4, 'code': dx_4}, {'pos': 5, 'code': dx_5}, {'pos': 6, 'code': dx_6}, {'pos': 7, 'code': dx_7}, {'pos': 8, 'code': dx_8}, {'pos': 9, 'code': dx_9}, {'pos': 10, 'code': dx_10}], recursive := true) from {{ ref('stg_ip') }}
union all
select 'outpatient' as setting, beneficiary_id, claim_id, segment, unnest([{'pos': 0, 'code': admitting_dx}, {'pos': 1, 'code': dx_1}, {'pos': 2, 'code': dx_2}, {'pos': 3, 'code': dx_3}, {'pos': 4, 'code': dx_4}, {'pos': 5, 'code': dx_5}, {'pos': 6, 'code': dx_6}, {'pos': 7, 'code': dx_7}, {'pos': 8, 'code': dx_8}, {'pos': 9, 'code': dx_9}, {'pos': 10, 'code': dx_10}], recursive := true) from {{ ref('stg_op') }}
union all
select 'carrier' as setting, beneficiary_id, claim_id, '1' as segment, unnest([{'pos': 1, 'code': dx_1}, {'pos': 2, 'code': dx_2}, {'pos': 3, 'code': dx_3}, {'pos': 4, 'code': dx_4}, {'pos': 5, 'code': dx_5}, {'pos': 6, 'code': dx_6}, {'pos': 7, 'code': dx_7}, {'pos': 8, 'code': dx_8}], recursive := true) from {{ ref('stg_carrier_claim') }}
) where code is not null
