"""Generate the dbt project's models from the validated SQL in sql/.

The legacy pipeline (``medicare-claims build``) remains the source of truth. This script turns every
``create or replace table|view <name> as <select>`` statement into a dbt model with ``ref()`` and
``source()`` dependencies and dbt vars in place of the ``$parameters``, so dbt and the legacy path run
exactly the same logic. ``tests/test_dbt_project.py`` fails if the generated models drift from sql/.

Run from the repository root: ``uv run python scripts/gen_dbt_models.py``.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SQL_DIR = ROOT / "sql"
MODELS = ROOT / "dbt" / "models"
MACROS = ROOT / "dbt" / "macros" / "claims_sql_macros.sql"

LAYER = {"01": "staging", "01b": "staging", "02": "dimensions", "03": "facts", "04": "marts", "05": "marts",
         "06": "marts", "07": "marts", "08": "audit"}
SOURCES = ["raw_beneficiary", "raw_inpatient", "raw_outpatient", "raw_carrier", "ref_ccs_dx"]
STRING_VARS = {"study_start", "study_end"}
FLOAT_VARS = {"top_share_percent", "iqr_multiplier", "paid_medium_min", "paid_high_min"}
LIST_VARS = {"ed_codes"}
HEADER = "-- GENERATED by scripts/gen_dbt_models.py from sql/{file}. Do not edit; change sql/ and regenerate.\n"
STATEMENT = re.compile(r"^create\s+or\s+replace\s+(table|view)\s+(\w+)\s+as\s+(.*)$", re.I | re.S)
MACRO = re.compile(r"^create\s+or\s+replace\s+macro\s+", re.I)


def statements(path: Path) -> list[str]:
    """Split a SQL file exactly as medicare_claims.model.run_sql_file does."""
    text = "\n".join(line for line in path.read_text(encoding="utf-8").splitlines() if not line.strip().startswith("--"))
    return [part.strip() for part in text.split(";") if part.strip()]


def render_var(name: str) -> str:
    if name in STRING_VARS:
        return f"'{{{{ var('{name}') }}}}'"
    if name in FLOAT_VARS:
        return f"cast({{{{ var('{name}') }}}} as double)"
    if name in LIST_VARS:
        return f"{{{{ duckdb_varchar_list(var('{name}')) }}}}"
    return f"{{{{ var('{name}') }}}}"


def build() -> dict[Path, str]:
    files = sorted(SQL_DIR.glob("[0-9][0-9]*.sql"))
    parsed: list[tuple[str, str, str, str]] = []  # (file, kind, name, body)
    macros: list[str] = []
    for path in files:
        for statement in statements(path):
            if MACRO.match(statement):
                macros.append(statement)
                continue
            match = STATEMENT.match(statement)
            if not match:
                raise ValueError(f"{path.name}: unsupported statement for dbt generation: {statement[:80]}")
            parsed.append((path.name, match.group(1).lower(), match.group(2), match.group(3)))
    models = {name for _, _, name, _ in parsed}
    out: dict[Path, str] = {}
    for file, kind, name, body in parsed:
        text = body
        for model in sorted(models, key=len, reverse=True):
            if model != name:
                text = re.sub(rf"(?<![\w.]){model}(?!\w)", f"{{{{ ref('{model}') }}}}", text)
        for source in SOURCES:
            text = re.sub(rf"(?<![\w.]){source}(?!\w)", f"{{{{ source('claims_raw', '{source}') }}}}", text)
        text = re.sub(r"\$([a-z_]+)", lambda m: render_var(m.group(1)), text)
        prefix = file.split("_")[0]
        layer = LAYER[prefix]
        materialized = "view" if kind == "view" else "table"
        out[MODELS / layer / f"{name}.sql"] = (HEADER.format(file=file)
                                               + f"{{{{ config(materialized='{materialized}') }}}}\n\n{text}\n")
    macro_body = ("{% macro create_claims_sql_macros() %}\n"
                  "-- DuckDB scalar macros used by the models, created in the target database before any model runs.\n"
                  + ";\n".join(macros) + ";\n{% endmacro %}")
    out[MACROS] = HEADER.format(file="01_staging.sql") + macro_body + "\n"
    return out


def main(check: bool = False) -> int:
    generated = build()
    stale = [p for p, text in generated.items() if not p.exists() or p.read_text(encoding="utf-8") != text]
    existing = {p for p in MODELS.rglob("*.sql")}
    orphans = sorted(existing - set(generated))
    if check:
        for p in stale:
            print(f"out of date: {p.relative_to(ROOT)}")
        for p in orphans:
            print(f"not generated from sql/: {p.relative_to(ROOT)}")
        return 1 if stale or orphans else 0
    for p in orphans:
        p.unlink()
    for p, text in generated.items():
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_text(text, encoding="utf-8")
    print(f"wrote {len(generated) - 1} models and the macro file")
    return 0


if __name__ == "__main__":
    sys.exit(main(check="--check" in sys.argv))
