"""Generate sql/01b_staging_unpivot.sql: wide CMS columns to long tables.

Run `python scripts/gen_wide_sql.py` after changing the column lists. The output is committed so the
pipeline needs no code generation at run time.
"""

from __future__ import annotations

from pathlib import Path

OUT = Path(__file__).resolve().parents[1] / "sql" / "01b_staging_unpivot.sql"


def structs(n: int, fields: dict[str, str]) -> str:
    items = []
    for i in range(1, n + 1):
        body = ", ".join(f"'{k}': {v.format(i=i)}" for k, v in fields.items())
        items.append(f"{{'line_num': {i}, {body}}}")
    return "[" + ", ".join(items) + "]"


def dx_positions(prefix_cols: list[str], n: int, admitting: bool) -> str:
    items = []
    if admitting:
        items.append("{'pos': 0, 'code': admitting_dx}")
    for i in range(1, n + 1):
        items.append(f"{{'pos': {i}, 'code': dx_{i}}}")
    return "[" + ", ".join(items) + "]"


def main() -> None:
    parts = ["-- GENERATED by scripts/gen_wide_sql.py. Do not edit by hand.",
             "-- Wide CMS columns (diagnoses, HCPCS positions, carrier line groups) to long tables."]

    def dx_long(setting: str, table: str, count: int, admitting: bool, segment: bool) -> str:
        seg = "segment" if segment else "'1' as segment"
        return (f"select '{setting}' as setting, beneficiary_id, claim_id, {seg}, "
                f"unnest({dx_positions([], count, admitting)}, recursive := true) from {table}")

    parts.append("create or replace table stg_dx_long as\nselect * from (\n"
                 + "\nunion all\n".join([
                     dx_long("inpatient", "stg_ip", 10, True, True),
                     dx_long("outpatient", "stg_op", 10, True, True),
                     dx_long("carrier", "stg_carrier_claim", 8, False, False),
                 ]) + "\n) where code is not null;")

    hcpcs_fields = {"code": 'norm_code("HCPCS_CD_{i}")'}
    parts.append(
        "create or replace table stg_hcpcs_long as\nselect * from (\n"
        "select 'inpatient' as setting, \"DESYNPUF_ID\" as beneficiary_id, \"CLM_ID\" as claim_id, "
        "coalesce(\"SEGMENT\", '1') as segment,\n"
        f"  unnest({structs(45, hcpcs_fields)}, recursive := true)\nfrom raw_inpatient\nunion all\n"
        "select 'outpatient' as setting, \"DESYNPUF_ID\" as beneficiary_id, \"CLM_ID\" as claim_id, "
        "coalesce(\"SEGMENT\", '1') as segment,\n"
        f"  unnest({structs(45, hcpcs_fields)}, recursive := true)\nfrom raw_outpatient\n"
        ") where code is not null;")

    line_fields = {
        "hcpcs": 'norm_code("HCPCS_CD_{i}")',
        "npi": '"PRF_PHYSN_NPI_{i}"',
        "tax_num": '"TAX_NUM_{i}"',
        "line_nch_pmt_amt": '"LINE_NCH_PMT_AMT_{i}"',
        "line_bene_ptb_ddctbl_amt": '"LINE_BENE_PTB_DDCTBL_AMT_{i}"',
        "line_bene_prmry_pyr_pd_amt": '"LINE_BENE_PRMRY_PYR_PD_AMT_{i}"',
        "line_coinsrnc_amt": '"LINE_COINSRNC_AMT_{i}"',
        "line_alowd_chrg_amt": '"LINE_ALOWD_CHRG_AMT_{i}"',
        "line_prcsg_ind_cd": '"LINE_PRCSG_IND_CD_{i}"',
        "line_dx": 'norm_code("LINE_ICD9_DGNS_CD_{i}")',
    }
    parts.append(
        "create or replace table stg_carrier_line as\n"
        "select beneficiary_id, claim_id, from_date, thru_date, line_num, hcpcs, npi, tax_num,\n"
        "  to_amt(line_nch_pmt_amt) as line_nch_pmt_amt, to_amt(line_bene_ptb_ddctbl_amt) as line_bene_ptb_ddctbl_amt,\n"
        "  to_amt(line_bene_prmry_pyr_pd_amt) as line_bene_prmry_pyr_pd_amt, to_amt(line_coinsrnc_amt) as line_coinsrnc_amt,\n"
        "  to_amt(line_alowd_chrg_amt) as line_alowd_chrg_amt, line_prcsg_ind_cd, line_dx\n"
        "from (\n"
        "  select \"DESYNPUF_ID\" as beneficiary_id, \"CLM_ID\" as claim_id, to_date8(\"CLM_FROM_DT\") as from_date,\n"
        "         to_date8(\"CLM_THRU_DT\") as thru_date,\n"
        f"         unnest({structs(13, line_fields)}, recursive := true)\n"
        "  from raw_carrier\n"
        ")\n"
        "-- CMS pads unused line slots with a 0.00 payment. A real line has a code, a non-zero payment or a performing NPI.\n"
        "where hcpcs is not null or coalesce(to_amt(line_nch_pmt_amt), 0) <> 0 or npi is not null\n"
        "qualify row_number() over (partition by beneficiary_id, claim_id, line_num order by from_date) = 1;")
    OUT.write_text("\n\n".join(parts) + "\n", encoding="utf-8")
    print(f"wrote {OUT} ({OUT.stat().st_size / 1024:.0f} KB)")


if __name__ == "__main__":
    main()
