"""Tableau package: aggregated extracts, an expected-KPI file for QA, and a generated field dictionary.

Tableau is not operated by this pipeline. The package prepares everything a person needs to build the
workbook and check it; see tableau/README.md for the manual checkpoint.
"""

from __future__ import annotations

from pathlib import Path

import duckdb
import pandas as pd

from medicare_claims.config import Config
from medicare_claims.export import datasets

EXTRACTS = ("kpi_annual", "annual_by_setting", "monthly_utilization", "monthly_payments", "condition_summary",
            "provider_review_facility", "readmission_review", "risk_tier_summary", "payment_concentration",
            "demographic_summary")

DESCRIPTIONS = {
    "year": "Calendar year (inpatient claims are dated by admission).",
    "year_month": "Calendar month, YYYY-MM.",
    "setting": "Care setting: inpatient, outpatient or carrier.",
    "claims": "Analytic claims (beneficiary + CLM_ID within a setting, segments merged).",
    "payment_amount": "Medicare trust fund payment: CLM_PMT_AMT (inpatient, outpatient) or LINE_NCH_PMT_AMT_1..13 (carrier). Synthetic. Not a cost.",
    "payment_total": "Sum of payment_amount across settings.",
    "beneficiaries": "Synthetic beneficiary rows in the year.",
    "member_years": "Member months divided by 12.",
    "members": "Eligible members in the month.",
    "admissions": "Continuous inpatient stays by admission date.",
    "ed_proxy_visits": "Outpatient claims with HCPCS 99281 to 99285. Proxy, not a validated ED measure.",
    "utilization_risk_tier": "Descriptive tier from prior-year information. Not CMS-HCC.",
    "review_flag": "Peer-quartile review flag. Not fraud or quality evidence.",
    "reason_codes": "Why a provider-year was flagged.",
    "provider_id": "Synthetic facility identifier (PRVDR_NUM).",
    "readmission_rate": "Readmitted eligible index stays / eligible index stays (30-day proxy).",
    "top_share": "Share of payment held by the highest-paid 5 percent of beneficiaries.",
    "condition_id": "AHRQ CCS 2015 category number, or 'unmapped'.",
    "condition_name": "AHRQ CCS category name, or a reason the code could not be grouped.",
    "prevalence": "Beneficiaries with the chronic condition flag / beneficiaries in the year.",
    "sex": "Sex from the beneficiary summary (BENE_SEX_IDENT_CD).",
    "race": "Race from the beneficiary summary (BENE_RACE_CD): White, Black, Other, Hispanic.",
    "age_band": "Age at the end of the year from the synthetic birth date.",
}


def field_dictionary(frames: dict[str, pd.DataFrame]) -> str:
    lines = ["# Field dictionary", "", "> CMS synthetic claims - not real patient or provider performance.", "",
             "Generated by `medicare-claims tableau`. One section per extract in `tableau/data/`.", ""]
    for name, frame in frames.items():
        lines += [f"## {name}.csv", "", f"{len(frame):,} rows. Aggregates only.", "", "| Field | Type | Meaning |", "|---|---|---|"]
        for column, dtype in frame.dtypes.items():
            kind = "number" if pd.api.types.is_numeric_dtype(dtype) else "boolean" if pd.api.types.is_bool_dtype(dtype) else "text"
            lines.append(f"| `{column}` | {kind} | {DESCRIPTIONS.get(str(column), '')} |")
        lines.append("")
    return "\n".join(lines)


def expected_kpis(frames: dict[str, pd.DataFrame]) -> pd.DataFrame:
    """Values a Tableau KPI worksheet must reproduce, one row per year and metric."""
    ann = frames["kpi_annual"]
    keep = ["beneficiaries", "claims", "payment_total", "payment_per_beneficiary", "admissions_per_1000_member_years",
            "ed_proxy_per_1000_member_years", "readmission_rate", "top_5pct_payment_share"]
    return ann.melt(id_vars="year", value_vars=keep, var_name="metric", value_name="expected_value").sort_values(["year", "metric"])


def build_package(con: duckdb.DuckDBPyConnection, config: Config, directory: Path | None = None) -> Path:
    target = directory or config.artifacts_root / "tableau"
    data = target / "data"
    data.mkdir(parents=True, exist_ok=True)
    ds = datasets(con, config)
    frames = {name: ds[name] for name in EXTRACTS}
    for name, frame in frames.items():
        frame.to_csv(data / f"{name}.csv", index=False)
    expected_kpis(frames).to_csv(target / "expected_kpis.csv", index=False)
    (target / "field_dictionary.md").write_text(field_dictionary(frames), encoding="utf-8")
    return target
